spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bank_db
    username: bank_user
    password: bank_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:db/migration/db.changelog-master.yaml

server:
  port: 8080

jwt:
  secret: "NDQ1YjM4NDM1NjRiNTM2Mzc1NjM0NTY0NTY3MzQ1NjQ1NjM0NTYzNDU2MzQ1NjM0NTYzNDU2MzQ1NjQ1Ng=="
  expiration: 86400000